### ISSUE TITLE
Implement safe nodecpp::string

### ISSUE THREAD

**Issue by nobugs-hare** [node-dot-cpp/memory-safe-cpp#14]
Suggested to base implementation on eastl . 

Suggested approach:
- take eastl1s basic_string<>; **whenever forking eastl file, make sure to make a comment within the forked file, with BOTH eastl version number, AND github's commit ID of the file**
- change the pointer to owning_ptr
- implement functions returning both pointers and safe pointers out of the string; functions returning safe pointers should have _safe suffix (example: c_str_safe()); 
- NB: zeroing of pointer within destructor will be done by destructor of owning_ptr<>.

**Comment by marcosbracco** [comment]
I added `_unsafe` suffix to unsafe overloads, and safe ones retain the original name.
Two reasons for this:
+ Operators and constructors can't get a name change, so I left only safe ones (the ones not taking raw pointers).
+ More than half of the overloads for methods like `assign`, `append`, `insert`, `replace`, and `find*` where already safe (didn't take any raw pointers)
+ Leaving safe methods with original names allow to use it as drop-in replacement of `std::string`, i.e. changing a typedef to switch between `std::string` and `safememory::string`. Things like `name.replace(name.begin() + 5, name.end(), "world!")` work perfectly safe because `begin()` and `end()` return safe iterators, and `string_literal` is implicitly constructed and used as argument.

If there are still reasons to use `_safe` on safe methods that I am not seeing, I can change it.

**Comment by marcosbracco** [comment]
@nobugs-hare  are you ok with comment above? Or maybe there is some other reasons in  favor of using '_safe'

**Comment by marcosbracco** [comment]
Done at 8148c201
