### ISSUE TITLE
Develop rules for unifying directory structure

### ISSUE THREAD

**Issue by divanchykhin** [node-dot-cpp/memory-safe-cpp#28]
We can take a s basis, for instance, this approach: [https://github.com/vector-of-bool/pitchfork/blob/spec/data/spec.bs](https://github.com/vector-of-bool/pitchfork/blob/spec/data/spec.bs). As a result, specific rules are to be developed and some restructuring may be required.

**Comment by marcosbracco** [comment]
The use of 'include' folder for public API headers is good. Most big projects now a days also add a subfolder inside include with the project name (i.e. include/nodecpp/<files>)
So user includes look like this:

`#include <nodecpp/map.h>`
`#include <nodecpp/safe_ptr.h>`

Makes easy to tell from witch library a file is, and also prevents name colission (i.e. with std <map>)

But the problem we currently have is that all files included by a public API header are also public API header. A public API header can't depend on a non-public header.
And currenly `safe_ptr.h` includes `safe_ptr_common.h` `safe_ptr_impl.h` and `safe_ptr_no_checks.h`, and they in turn include `foundation.h`, that in turn includes a lot of other headers, making almost everything public api header.
So my proposal would be to use ~~Merged~~ Separate Header Placement from the [PFL](https://github.com/vector-of-bool/pitchfork/blob/spec/data/spec.bs) document above, with the following details:
* Use `include/nodecpp` for public api files that user needs direct interaction (`map.h`, `safe_ptr.h`) and a subfolder `include/nodecpp/internal` to put files user doesn't need to see (`safe_ptr_common.h` `safe_ptr_impl.h` and `safe_ptr_no_checks.h`).
* Non public api headers go to `src` folder like mentioned in ~~Merged~~ Separate Header Placement at PFL. Currently none.
* ~~Code inside `src` doesn't necesarily have the same folder structure that `include` one. Code inside `src` will be few enought not to need folder structure for the time being.~~
* Code inside `src` must have `.h/.ccp` pairs as components. That is a .cpp file should only implements things declared in a .h of the same name at the same folder (a private header) or a .h with the same name under the same folder path under `include` (a public header). There will be .h files without a corresponding .cpp (both public and private).
* Submodules probably should go to ~~`libs/iibmalloc` and `libs/foundation`. While this doesn't exactly match what is supposed to be at `libs` from PFL, it's close.~~ `external/iibmalloc` and `external/foundation` (at project `iibmalloc`).

**Comment by nobugs-hare** [comment]
- I don't really see how it is "Merged Header Placement" (for "Merged", there is no 'include' folder at all). Let's clarify.
- as our iibmalloc and foundation are actually *projects*, they cannot be *submodules*. My understanding is that they should go to `external` folder, let's discuss. 
- one thing which is missing from our current layout is *mandatory* .h/.cpp pairs as *components*.

Let's discuss it further

**Comment by marcosbracco** [comment]
I agree, updated the text above.
I will take the oportunity to say I believe `iibmalloc` and `foundation` shouldn't be separate repos. I think a single repo makes more sence for closely related projects. [Here](https://llvm.org/docs/Proposals/GitHubMove.html) there is some rationale and pros/cons on using a **monorepo** from llvm project (whose major con for monorepo was their huge size).

And around namespaces, I believe everything in the public api (all types and functions used directly by the user) should fall in a single namespace (where it should be `namespace nodecpp` or `namespace safememory`  or something else is TBD). Nested or sub namespaces must be used for private things not to be directly used by the end user (like `namespace nodecpp::internal`).
The rationale for this is make life easier to user and better organize the options that IDE autocomplete functionality will show.

**Comment by nobugs-hare** [comment]
@marcosbracco re monorepo - it is quite a non-trivial issue (on the one hand, monorepo does simplify refactoring - but the exact flip side of it is increased coupling which is a Bad Thing(tm)). Also, as APIs at the boundaries malloc/safe-mem/node.cpp are not expected to change too often - argumentation from LLVM doesn't apply directly.

In any case, we don't have time to change it now, so let's keep it as is for now and see later.

**Comment by marcosbracco** [comment]
@nobugs-hare ok for monorepo.
As to better suport my point on namespace I am attaching an screenshot of autocomplete I get when I type 'soft_'. Most of that shouldn't be seen by user. Only 'soft_ptr' and 'soft_this_ptr' make sence there. And 'soft_ptr' is not even there, you need to scroll up to find it.
Not saying we should make it now, but we need to keep it in mind.

<img width="369" alt="soft_ptr" src="https://user-images.githubusercontent.com/11540434/73395822-fe8b8f80-42be-11ea-8f72-d95e88b4e9ff.png">

**Comment by nobugs-hare** [comment]
- Agree on implementation namespaces (let's specify that implementation details go into `detail` namespace); please add it to https://github.com/node-dot-cpp/memory-safe-cpp/issues/28#issuecomment-577882441 . 
- I do NOT agree on pushing everything into nodecpp namespace. Instead (if it is feasible in practice), I'd prefer to have separate foundation/safe_memory/... namespaces, BUT have nodecpp namespace `using` those parts from foundation/safe_memory/... which are exposed to nodecpp user. In other words, (a) safe_memory SHOULD NOT know about nodecpp namespace; (b) from point of view of the user of nodecpp, she can write `nodecpp:soft_ptr<>`. 
- I suggest to remove "There will be .h files without a corresponding .cpp (both public and private).", replacing it with "if there is nothing to be put into .cpp, it should be present, containing nothing but a single include directive including its own .h"; per PFL, this is a good practice "to ensure that the `list.hpp` file will compile in isolation, ensuring that the header has the necessary `#include` directives and/or forward declarations."; and from my perspective, it reduces the barrier to start moving things to .cpp (which is a Good Thing(tm) for quite a bit of our stuff which currently resides in .h). 
- we have to think about plug-ins and non-core modules (see respective issues) - they should also map to Conan packages. My current suggestion would be to put them under extras/plugins and extras/packages , but if there are any other considerations - let's discuss. 
- there is a question on "what to do if component header has to be split into several files"; I suggest to allow public headers such as "soft_ptr.h" and "soft_ptr_detail.h". 
- if public/private headers do have the same names - we should EXPLICITLY prohibit having both private and public headers for the same .cpp (otherwise it will be Damn Mess(tm)). Probably I'd go further and say that private headers should have "_private" suffix to them ("something_private.h"), to avoid potential for very messy mistakes. 
- we SHOULD have one exception to the rules - if we refactor 3rd-party stuff (such as eastl) then we put them into one folder, but within that folder we do keep original directory structure (including file names etc, etc,).

**Comment by marcosbracco** [comment]
Pushed file `library/doc/DIRECTORY-LAYOUT.md` with all comments from this issue.
