### ISSUE TITLE
Add support for no-side-effect functions

### ISSUE THREAD

**Issue by divanchykhin** [node-dot-cpp/memory-safe-cpp#33]
A **no-side-effect function** has no input other than its parameters and changes nothing outside its scope. As a result, no-side-effect function can call only no-side-effect functions.

Examples of side-effect functions are, in particular, all system calls (think about time() as an external input and write() as changing the outside state).

An explicit exclusion for practical purposes is granted to trace().

In addition, support for _no-side-read-effect_ and _no-side-write-effect_ can be added for future purposes (lower priority). Example of the first is trace(), and of the second is time().

**Also**: respective rule should be added.

**Comment by marcosbracco** [comment]
We may have some issues here as function body is not always available for analisys.
Function body may be in a different translation unit.
So we may detect it automatically for functions defined inline or in the current translation unit, or to add some markup to the function declaration.
I believe that adding some markup will be problematic becuase we need to also add markup to every function called from there and this markup will propagate a lot.
For the kind of uses this has now, probably requiring the function to have the body inline will not be harmful.
@nobugs-hare what do you think?

**Comment by nobugs-hare** [comment]
According to our Big Fat Principle(tm) of "all analysis MUST be local" (otherwise a local change can easily lead to a compile error miles away) - it should be markup. As for propagation:
- propagation will occur in a manner similar to that of _const_
- as of now, developers-using-Node.cpp need this no_side_effects modifier only for hashing/etc. functions - which are usually pretty much self-contained, so no THAT MUCH propagation will realistically occur. NB: we'll still need to mark many functions in say nodecpp::string as no_side_effects, but it won't affect developers too much.

**Comment by marcosbracco** [comment]
Done. See #34
